image:
  repository: ghcr.io/naoyahorita-i4/kong # GHCRを指定
  tag: "3.10.0.2-20250520-ubuntu" # 自分で付与したtagを指定
  imagePullSecrets:
    - name: regcred  # GHCRに接続するためのsecretをkubectlで作成しておく

secretVolumes:
- kong-cluster-cert

admin:
  enabled: false

env:
  role: data_plane
  database: "off"
  cluster_mtls: pki
  cluster_control_plane: 81fc5cbadc.us.cp0.konghq.com:443
  cluster_dp_labels: "type:docker-kubernetesOS"
  cluster_server_name: 81fc5cbadc.us.cp0.konghq.com
  cluster_telemetry_endpoint: 81fc5cbadc.us.tp0.konghq.com:443
  cluster_telemetry_server_name: 81fc5cbadc.us.tp0.konghq.com
  cluster_cert: /etc/secrets/kong-cluster-cert/tls.crt
  cluster_cert_key: /etc/secrets/kong-cluster-cert/tls.key
  lua_ssl_trusted_certificate: system
  konnect_mode: "on"
  vitals: "off"
  nginx_worker_processes: "1"
  upstream_keepalive_max_requests: "100000"
  nginx_http_keepalive_requests: "100000"
  proxy_access_log: "off"
  dns_stale_ttl: "3600"
  router_flavor: expressions

ingressController:
  enabled: false
  installCRDs: false

resources:
  requests:
    cpu: 1
    memory: "2Gi"

serviceMonitor: # prometheusとの接続
  enabled: true
  labels:
    release: prometheus-stack

status: # health checkの有効化
  enabled: true
  http:
    enabled: true
    containerPort: 8100