name: Docker Image Workflow

on:
  push:
    branches:
      - main  # メインブランチにPushされた場合フローをキック

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    strategy:
      matrix:
        platform:
          - linux/arm64 # k8sクラスタのCPUアーキテクチャに合わせる

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Pull Docker image
      run: docker pull kong/kong-gateway:3.10.0.2-20250520-ubuntu # OSS版ではなくKongのEnterpriseイメージを選択

    - name: Log in to GHCR
      run: echo "${{ secrets.PAT }}" | docker login ghcr.io -u naoyahorita-i4 --password-stdin # 事前にGitHubでPAT作成

    - name: Tag Docker image
      run: docker tag kong/kong-gateway:3.10.0.2-20250520-ubuntu ghcr.io/naoyahorita-i4/kong:3.10.0.2-20250520-ubuntu

    - name: Push Docker image to GHCR
      run: docker push ghcr.io/naoyahorita-i4/kong:3.10.0.2-20250520-ubuntu

    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget -O trivy_latest.deb https://github.com/aquasecurity/trivy/releases/download/v0.62.1/trivy_0.62.1_Linux-ARM64.deb
        sudo dpkg -i trivy_latest.deb

    - name: Run Trivy scan # 脆弱性スキャン
      id: trivy
      run: |
        trivy image --quiet --severity HIGH,CRITICAL ghcr.io/naoyahorita-i4/kong:3.10.0.2-20250520-ubuntu > trivy_report.txt
        cat trivy_report.txt

    - name: Check for vulnerabilities
      run: |
        last_line=$(tail -n 2 trivy_report.txt)
        if [[ "$last_line" == *"'0': Clean"* ]]; then
          echo "No vulnerabilities found."
        else
          echo "Vulnerabilities found, deleting image..."
          docker rmi ghcr.io/naoyahorita-i4/kong:3.10.0.2-20250520-ubuntu || true
          exit 1
        fi