name: Docker Image Workflow

on:
  push:
    branches:
      - main  # メインブランチにPushされた場合フローをキック

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Pull Docker image
      run: docker pull kong/kong:latest

    - name: Log in to GHCR
      run: echo "${{ secrets.PAT }}" | docker login ghcr.io -u naoyahorita-i4 --password-stdin

    - name: Tag Docker image
      run: docker tag kong/kong:latest ghcr.io/naoyahorita-i4/kong:latest

    - name: Push Docker image to GHCR
      run: docker push ghcr.io/naoyahorita-i4/kong:latest

    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget -O trivy_0.21.2_Linux-64bit.deb https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.21.2_Linux-64bit.deb
        sudo dpkg -i trivy_0.21.2_Linux-64bit.deb

    - name: Run Trivy scan
      id: trivy
      run: trivy image ghcr.io/naoyahorita-i4/kong:latest

    - name: Check for vulnerabilities
      run: |
        vulnerabilities=$(trivy image --quiet --severity HIGH,CRITICAL ghcr.io/naoyahorita-i4/kong:latest | grep "Total: 0" || true)
        if [[ "$vulnerabilities" == "" ]]; then
          echo "Vulnerabilities found, deleting image..."
          docker rmi ghcr.io/naoyahorita-i4/kong:latest || true
          exit 1
        else
          echo "No vulnerabilities found."
        fi